// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLQXjKNfqAQimwY0PnnNpHpQG1gvmvwZg',
    appId: '1:711562641803:web:24cd14cfe53e9b022fef8e',
    messagingSenderId: '711562641803',
    projectId: 'flutter-template-826b1',
    authDomain: 'flutter-template-826b1.firebaseapp.com',
    databaseURL: 'https://flutter-template-826b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-template-826b1.firebasestorage.app',
    measurementId: 'G-DRWY1CFJQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuqKYpgchjeW9c_o8dv_5Nv0OfsNbQQeI',
    appId: '1:711562641803:android:b7db4d1b8e3964332fef8e',
    messagingSenderId: '711562641803',
    projectId: 'flutter-template-826b1',
    databaseURL: 'https://flutter-template-826b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-template-826b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8gPA4WJ8vMEi5IYUA5OwYaCbn6GRcOsY',
    appId: '1:711562641803:ios:19e99b674c50fd122fef8e',
    messagingSenderId: '711562641803',
    projectId: 'flutter-template-826b1',
    databaseURL: 'https://flutter-template-826b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-template-826b1.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8gPA4WJ8vMEi5IYUA5OwYaCbn6GRcOsY',
    appId: '1:711562641803:ios:19e99b674c50fd122fef8e',
    messagingSenderId: '711562641803',
    projectId: 'flutter-template-826b1',
    databaseURL: 'https://flutter-template-826b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-template-826b1.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLQXjKNfqAQimwY0PnnNpHpQG1gvmvwZg',
    appId: '1:711562641803:web:b6b8b699941022e42fef8e',
    messagingSenderId: '711562641803',
    projectId: 'flutter-template-826b1',
    authDomain: 'flutter-template-826b1.firebaseapp.com',
    databaseURL: 'https://flutter-template-826b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-template-826b1.firebasestorage.app',
    measurementId: 'G-HC0D7HHJEH',
  );
}
